services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
    ports: ["9200:9200","9300:9300"]
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ulimits:
      memlock: { soft: -1, hard: -1 }

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.0
    environment: [ ELASTICSEARCH_HOSTS=http://elasticsearch:9200 ]
    ports: ["5601:5601"]
    depends_on: [elasticsearch]

  backend:
    build: ../backend
    env_file: ../.env
    working_dir: /app
    volumes:
      - ../backend:/app
      - ../data:/data
      - ../search:/search
    ports: ["8000:8000"]
    depends_on: [elasticsearch]
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    
volumes:
  esdata: